apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: counter-service-pipeline
spec:
  tasks:
    - name: lint
      taskRef:
        name: lint-task

    - name: test
      runAfter: ["lint"]
      taskRef:
        name: test-task

    - name: build
      runAfter: ["test"]
      taskRef:
        name: build-task

    - name: deploy
      runAfter: ["build"]
      taskRef:
        name: deploy-task
