apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint-task
spec:
  steps:
    - name: lint
      image: python:3.9-slim
      script: |
        python -m pip install --upgrade pip
        pip install flake8
        flake8 service
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-task
spec:
  steps:
    - name: test
      image: python:3.9-slim
      script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pytest
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-task
spec:
  steps:
    - name: build-image
      image: quay.io/buildah/stable
      securityContext:
        privileged: true
      script: |
        buildah bud -t counter-service:latest .
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-task
spec:
  steps:
    - name: deploy
      image: bitnami/kubectl:latest
      script: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task
spec:
  workspaces:
    - name: source
  steps:
    - name: cleanup
      image: alpine:3
      env:
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsUser: 0
      script: |
        set -eu
        echo "Removing all files from ${WORKSPACE_SOURCE_PATH} ..."

        if [ -d "${WORKSPACE_SOURCE_PATH}" ]; then
          rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*
          rm -rf "${WORKSPACE_SOURCE_PATH}"/.[!.]*
          rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
        fi
